server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/toyboard
    username: root
    password: root

#    hikari:
#      maximum-pool-size: 50
#      minimum-idle: 2
#      data-source-properties:
#        cachePrepStmts: true
#        prepStmtCacheSize: 500
#        prepStmtCacheSqlLimit: 2048
#        useServerPrepStmts: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        enable_lazy_load_no_trans: true
